# Label configurations for PRs based on changed files
# Updated for actions/labeler@v5 syntax

frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*'
      - 'index.html'
      - 'vite.config.js'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'public/**/*.svg'

workflow:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'

automation:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/labeler.yml'
      - '.github/workflows/labeler.yml'
      - '.github/workflows/issue-labeler.yml'

css:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*.css'
      - 'tailwind.config.js'
      - 'postcss.config.js'
