name: "🐛 Technical Bug Report"
description: "Report a technical error or broken functionality."
title: "[BUG]: "
labels: ["bug", "technical"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "How can we see the bug ourselves?"
      placeholder: "1. Go to '/guides'\n2. Click on 'Chipset'\n3. See error..."
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Where did this happen?"
      placeholder: "e.g., Localhost (mkdocs serve) or GitHub Pages (Production)"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: "Browser & OS"
      description: "e.g., Chrome 120 on Windows 11"
    validations:
      required: true
